newspaper/urls.py
from django.urls import path

from newspaper.views import (
    index,
    TopicListView,
    NewspaperListView,
    RedactorsListView,
    NewspaperDetailView,
    RedactorsDetailView,
    TopicCreateView,
    NewspaperCreateView,
    RedactorsCreateView,
    TopicUpdateView,
    TopicDeleteView,
    NewspaperUpdateView,
    NewspaperDeleteView,
    RedactorsDeleteView,
)

urlpatterns = [
    path("", index, name="index"),

    path(
        "topics/",
        TopicListView.as_view(),
        name="topics-list"
    ),
    path(
        "topics/create/",
        TopicCreateView.as_view(),
        name="topics-create"
    ),
    path(
        "topics/<int:pk>/update/",
        TopicUpdateView.as_view(),
        name="topic-update"
    ),
    path(
        "topics/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete"
    ),

    path(
        "newspaper/",
        NewspaperListView.as_view(),
        name="newspapers-list"
    ),
    path(
        "newspaper/<int:pk>/",
        NewspaperDetailView.as_view(),
        name="newspaper-detail"
    ),
    path(
        "newspaper/create/",
        NewspaperCreateView.as_view(),
        name="newspaper-create"
    ),
    path(
        "newspaper/<int:pk>/update/",
        NewspaperUpdateView.as_view(),
        name="newspaper-update"
    ),
    path(
        "newspaper/<int:pk>/delete/",
        NewspaperDeleteView.as_view(),
        name="newspaper-delete"
    ),

    path(
        "redactors/",
        RedactorsListView.as_view(),
        name="redactors-list"
    ),
    path(
        "redactors/<int:pk>/",
        RedactorsDetailView.as_view(),
        name="redactors-detail"
    ),
    path(
        "redactors/create/",
        RedactorsCreateView.as_view(),
        name="redactor-create"
    ),
    path(
        "redactors/<int:pk>/delete",
        RedactorsDeleteView.as_view(),
        name="redactors-delete"
    ),

]

app_name = "newspaper"

newspaper_agency/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path("", include("newspaper.urls", namespace="newspaper")),
                  path("registration/", include("django.contrib.auth.urls")),

              ] + debug_toolbar_urls()

templates/includes/footer.html
{% load static %}
<!-- -------- START FOOTER 5 w/ DARK BACKGROUND ------- -->
<footer class="footer py-5">
  <div class="container z-index-1 position-relative">
    <div class="row">
      <div class="col-lg-4 me-auto mb-lg-0 mb-4 text-lg-start text-center">
        <ul class="nav flex-row ms-n3 justify-content-lg-start text-center justify-content-center mb-4 mt-sm-0">
          <p>
            &copy; <a href="https://mate.academy/"
                      target="_blank">Havrylyshyn Ivan</a> - Mate
            Academy.
          </p>
        </ul>
      </div>
      {% if request.path == '/' %}

        <div class="col-lg-4 ms-auto text-lg-end text-center">

          <p style="text-align: center;">You have visited this page {{ num_visits }}
            time{{ num_visits|pluralize }}.</p>

          <hr class="vertical dark">
        </div>
      {% endif %}
      <div class="col-lg-4 ms-auto text-lg-end text-center">
        <a href="javascript:;" target="_blank" class="text-dark me-xl-4 me-4 opacity-5">
          <span class="fab fa-linkedin"></span>
        </a>
        <a href="javascript:;" target="_blank" class="text-dark me-xl-4 me-4 opacity-5">
          <span class="fab fa-facebook"></span>
        </a>
        <a href="javascript:;" target="_blank" class="text-dark opacity-5">
          <span class="fab fa-github"></span>
        </a>
      </div>

      </ul>
    </div>
  </div>
</footer>

templates/includes/footer_fullscreen.html
{% load static %}

<footer class="footer py-5">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 mb-4 mx-auto text-center">
        <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
          Company
        </a>
        <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
          About Us
        </a>
        <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
          Team
        </a>
        <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
          Products
        </a>
        <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
          Blog
        </a>
        <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
          Pricing
        </a>
      </div>
      <div class="col-lg-8 mx-auto text-center mb-4 mt-2">
        <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
          <span class="text-lg fab fa-linkedin"></span>
        </a>
        <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
          <span class="text-lg fab fa-twitter"></span>
        </a>
        <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
          <span class="text-lg fab fa-facebook"></span>
        </a>
        <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
          <span class="text-lg fab fa-github"></span>
        </a>
      </div>
    </div>
    <div class="row">
      <div class="col-8 mx-auto text-center mt-1">
        <p class="mb-0 text-secondary">
          &copy; <a href="" target="_blank">Havrylyshyn Ivan</a> - Mate Academy.
        </p>
      </div>
    </div>
  </div>
</footer>

templates/includes/navigation.html
{% load static %}
<!-- Navbar -->
<div class="container position-sticky z-index-sticky top-0">
  <div class="row">
    <div class="col-12">
      <nav
          class="navbar navbar-expand-lg  blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
        <div class="container-fluid px-0">
          <a class="navbar-brand font-weight-bolder ms-sm-3"
             href="/" rel="tooltip"
             title="Designed and Coded by Havrylyshyn Ivan" data-placement="bottom">
            Best Newspaper Agency
          </a>
          <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse"
                  data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false"
                  aria-label="Toggle navigation">
            <span class="navbar-toggler-icon mt-2">
              <span class="navbar-toggler-bar bar1"></span>
              <span class="navbar-toggler-bar bar2"></span>
              <span class="navbar-toggler-bar bar3"></span>
            </span>
          </button>


          <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 w-100" id="navigation">
            <ul class="navbar-nav navbar-nav-hover ms-lg-12 ps-lg-5 w-100">


              <li class="nav-item dropdown dropdown-hover mx-2">
                <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center"
                   href="javascript:;" aria-expanded="false">
                  <a href="{% url 'newspaper:topics-list' %}">Topics</a>
                </a>
              </li>

              <li class="nav-item dropdown dropdown-hover mx-2">
                <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center"
                   href="javascript:;" aria-expanded="false">
                  <a href="{% url 'newspaper:newspapers-list' %}">Newspapers</a>
                </a>
              </li>

              <li class="nav-item dropdown dropdown-hover mx-2">
                <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center"
                   href="javascript:;" aria-expanded="false" >
                  <a href="{% url 'newspaper:redactors-list' %}">Redactors
                </a>
                </a>
              </li>
              {% if request.user.is_authenticated %}
                <li class="nav-item ms-lg-auto">
                  <a class="nav-link nav-link-icon me-2"
                     href="{% url 'logout' %}">
                    <i class="fa fa-sign-out me-1"></i>
                    <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip"
                       data-bs-placement="bottom" title="Logout">Logout</p>
                  </a>
                </li>
              {% else %}
                <li class="nav-item ms-lg-auto">
                  <a class="nav-link nav-link-icon me-2"
                     href="{% url 'login' %}">
                    <i class="fa fa-sign-in me-1"></i>
                    <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip"
                       data-bs-placement="bottom" title="Login">Login</p>
                  </a>
                </li>
              {% endif %}

            </ul>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->
    </div>
  </div>
</div>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination" >

      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?{% query_transform request page=page_obj.previous_page_number %}">prev</a>
        </li>
      {% endif %}


      <li class="page-item">
        <span class="page-link active "> {{ page_obj.number }} of {{ paginator.num_pages }}</span>
      </li>


      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?{% query_transform request page=page_obj.next_page_number %}">next</a>
        </li>
      {% endif %}

  </ul>
{% endif %}

templates/includes/scripts.html
  {% load static %}
  
<!-- Core JS Files -->
<script src="{% static 'js/core/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/perfect-scrollbar.min.js' %}"></script>

<!-- Plugins -->
<script src="{% static 'js/plugins/parallax.min.js' %}"></script>
<script src="{% static 'js/plugins/choices.min.js' %}"></script>
<script src="{% static 'js/plugins/countup.min.js' %}"></script>
<script src="{% static 'js/plugins/prism.min.js' %}"></script>
<script src="{% static 'js/plugins/flatpickr.min.js' %}"></script>
<script src="{% static 'js/plugins/moment.min.js' %}"></script>
<script src="{% static 'js/plugins/rellax.min.js' %}"></script>
<script src="{% static 'js/plugins/tilt.min.js' %}"></script>
<script src="{% static 'js/plugins/typedjs.js' %}"></script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>

<script src="{% static 'js/soft-design-system.min.js' %}" type="text/javascript"></script>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% if user.is_authenticated %}
    <li class="list-group-item">
      User{{ user.username }}
    </li>
    <li class="list-group-item">
      <a href="{% url 'logout' %}">Logout</a>
    </li>
  {% else %}
    <li class="list-group-item">
      <a href="{% url 'login' %}">Login</a>
    </li>
  {% endif %}
  <br>
  <li class="list-group-item">
    <a href="{% url 'newspaper:index' %}">Home</a>
  </li>
  <li class="list-group-item">
    <a href="{% url 'newspaper:redactors-list' %}">All redactors</a>
  </li>
  <li class="list-group-item">
    <a href="{% url 'newspaper:newspapers-list' %}">All newspapers</a>
  </li>
  <li class="list-group-item">
    <a href="{% url 'newspaper:topics-list' %}">All topics</a>
  </li>
</ul>