newspaper/urls.py
from django.urls import path

from newspaper.views import (
    index,
    TopicListView,
    NewspaperListView,
    RedactorsListView,
    NewspaperDetailView,
    RedactorsDetailView,
    TopicCreateView,
    NewspaperCreateView,
    RedactorsCreateView,
    TopicUpdateView,
    TopicDeleteView,
    NewspaperUpdateView,
    NewspaperDeleteView,
    RedactorsDeleteView,
)

urlpatterns = [
    path("", index, name="index"),

    path(
        "topics/",
        TopicListView.as_view(),
        name="topics-list"
    ),
    path(
        "topics/create/",
        TopicCreateView.as_view(),
        name="topics-create"
    ),
    path(
        "topics/<int:pk>/update/",
        TopicUpdateView.as_view(),
        name="topic-update"
    ),
    path(
        "topics/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete"
    ),

    path(
        "newspaper/",
        NewspaperListView.as_view(),
        name="newspapers-list"
    ),
    path(
        "newspaper/<int:pk>/",
        NewspaperDetailView.as_view(),
        name="newspaper-detail"
    ),
    path(
        "newspaper/create/",
        NewspaperCreateView.as_view(),
        name="newspaper-create"
    ),
    path(
        "newspaper/<int:pk>/update/",
        NewspaperUpdateView.as_view(),
        name="newspaper-update"
    ),
    path(
        "newspaper/<int:pk>/delete/",
        NewspaperDeleteView.as_view(),
        name="newspaper-delete"
    ),

    path(
        "redactors/",
        RedactorsListView.as_view(),
        name="redactors-list"
    ),
    path(
        "redactors/<int:pk>/",
        RedactorsDetailView.as_view(),
        name="redactors-detail"
    ),
    path(
        "redactors/create/",
        RedactorsCreateView.as_view(),
        name="redactor-create"
    ),
    path(
        "redactors/<int:pk>/delete",
        RedactorsDeleteView.as_view(),
        name="redactors-delete"
    ),

]

app_name = "newspaper"

newspaper_agency/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path("", include("newspaper.urls", namespace="newspaper")),
                  path("registration/", include("django.contrib.auth.urls")),

              ] + debug_toolbar_urls()

newspaper/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class Topic(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return self.name


class Redactor(AbstractUser):
    years_of_experience = models.IntegerField(
        default=0,
        null=True,
        blank=True
    )

    class Meta:
        ordering = ("username",)

    def __str__(self):
        return f"{self.username}: ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("newspaper:redactors-detail", args=[str(self.id)])


class Newspaper(models.Model):
    title = models.CharField(max_length=255)
    context = models.TextField()
    published_date = models.DateTimeField(auto_now_add=True)
    topic = models.ForeignKey(
        Topic,
        on_delete=models.CASCADE,
        related_name="newspapers"
    )
    publishers = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="newspapers"
    )

    def display_authors(self):
        return ', '.join([author.username for author in self.publishers.all()])

    display_authors.short_description = 'Authors'

    class Meta:
        ordering = ("-published_date",)

    def __str__(self):
        return f"{self.topic} {self.title}"

    def get_absolute_url(self):
        return reverse("newspaper:newspaper-detail", args=[str(self.id)])

newspaper/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms

from newspaper.models import Redactor, Newspaper


class RedactorCreateForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Redactor
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "years_of_experience",
        )


class NewspaperForm(forms.ModelForm):
    publishers = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Newspaper
        fields = "__all__"


class NewspapersSearchForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by title"
            }
        )
    )


class RedactorSearchForm(forms.Form):
    username = forms.CharField(
        max_length=256,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by username"
            }
        )
    )


class TopicSearchForm(forms.Form):
    name = forms.CharField(
        max_length=256,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by topic"
            }
        )
    )

newspaper/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from newspaper.forms import (
    RedactorCreateForm,
    NewspaperForm,
    NewspapersSearchForm,
    RedactorSearchForm,
    TopicSearchForm,
)
from newspaper.models import Topic, Newspaper, Redactor


# Create your views here.
def index(request: HttpRequest) -> HttpResponse:
    num_topics = Topic.objects.count()
    num_redactors = Redactor.objects.count()
    num_newspapers = Newspaper.objects.count()
    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1
    contex = {
        "num_topics": num_topics,
        "num_redactors": num_redactors,
        "num_newspapers": num_newspapers,
        "num_visits": num_visits + 1,

    }
    return render(request, "newspaper/index.html", context=contex)


class TopicListView(LoginRequiredMixin, generic.ListView):
    model = Topic
    template_name = "newspaper/topics_list.html"
    context_object_name = "topics_list"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        contex = super(TopicListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", )
        contex["search_form"] = TopicSearchForm(
            initial={"name": name}
        )
        return contex

    def get_queryset(self):
        queryset = Topic.objects.all()
        form = TopicSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class TopicCreateView(LoginRequiredMixin, generic.CreateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("newspaper:topics-list")
    template_name = "newspaper/topic_form.html"


class TopicUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("newspaper:topics-list")
    template_name = "newspaper/topic_form.html"


class TopicDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Topic
    template_name = "newspaper/topic_confirm_delete.html"
    success_url = reverse_lazy("newspaper:topics-list")


class NewspaperListView(LoginRequiredMixin, generic.ListView):
    model = Newspaper
    template_name = "newspaper/newspaper_list.html"
    context_object_name = "newspaper_list"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        contex = super(NewspaperListView, self).get_context_data(**kwargs)
        title = self.request.GET.get("title", )
        contex["search_form"] = NewspapersSearchForm(
            initial={"title": title}
        )
        return contex

    def get_queryset(self):
        queryset = Newspaper.objects.select_related("topic")
        form = NewspapersSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(title__icontains=form.cleaned_data["title"])
        return queryset


class NewspaperDetailView(LoginRequiredMixin, generic.DetailView):
    model = Newspaper
    template_name = "newspaper/newspaper_detail.html"


class NewspaperCreateView(LoginRequiredMixin, generic.CreateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("newspaper:newspapers-list")
    template_name = "newspaper/newspaper_form.html"


class NewspaperUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Newspaper
    form_class = NewspaperForm
    template_name = "newspaper/newspaper_form.html"


class NewspaperDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Newspaper
    template_name = "newspaper/newspaper_confirm_delete.html"
    success_url = reverse_lazy("newspaper:newspapers-list")


class RedactorsListView(LoginRequiredMixin, generic.ListView):
    model = Redactor
    template_name = "newspaper/redactors_list.html"
    context_object_name = "redactors_list"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        contex = super(RedactorsListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", )
        contex["search_form"] = RedactorSearchForm(
            initial={"username": username}
        )
        return contex

    def get_queryset(self):
        queryset = Redactor.objects.all()
        form = RedactorSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )
        return queryset


class RedactorsDetailView(LoginRequiredMixin, generic.DetailView):
    model = Redactor
    template_name = "newspaper/redactors_detail.html"


class RedactorsCreateView(LoginRequiredMixin, generic.CreateView):
    model = Redactor
    form_class = RedactorCreateForm
    template_name = "newspaper/redactor_form.html"


class RedactorsDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Redactor
    template_name = "newspaper/redactor_confirm_delete.html"
    success_url = reverse_lazy("newspaper:redactors-list")

templates/newspaper/index.html
{% extends 'layouts/base_sections.html' %}
{% load static %}

{% block title %} Material Kit 2 by Havrylyshyn Ivan {% endblock title %}

{% block body %} class="index-page bg-gray-200" {% endblock body %}

{% block content %}

  <header class="header-2">
    <div class="page-header min-vh-75 relative"
         style="background-image: url('{% static 'img/curved-images/curved15.jpg' %}')">
      <div class="container">
        <div class="row">
          <div class="col-lg-7 text-center mx-auto">
            <h1 class="text-white pt-3 mt-n5">The Best Newspaper Agency</h1>
            <p class="lead text-white mt-3">Lot of news <br/> Best around the world. </p>
          </div>
        </div>
      </div>

      <div class="position-absolute w-100 z-index-1 bottom-0">
        <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
             viewBox="0 24 150 40" preserveAspectRatio="none" shape-rendering="auto">
          <defs>
            <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z"/>
          </defs>
          <g class="moving-waves">
            <use xlink:href="#gentle-wave" x="48" y="-1" fill="rgba(255,255,255,0.40"/>
            <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.35)"/>
            <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.25)"/>
            <use xlink:href="#gentle-wave" x="48" y="8" fill="rgba(255,255,255,0.20)"/>
            <use xlink:href="#gentle-wave" x="48" y="13" fill="rgba(255,255,255,0.15)"/>
            <use xlink:href="#gentle-wave" x="48" y="16" fill="rgba(255,255,255,0.95"/>
          </g>
        </svg>
      </div>
    </div>
  </header>


  <section class="pt-3 pb-4" id="count-stats">
    <div class="container">
      <div class="row">
        <div class="col-lg-9 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
          <div class="row">
            <div class="col-md-4 position-relative">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary"><span id="state1" countTo="{{ num_topics }}">0</span>+</h1>
                <h5 class="mt-3">Topics</h5>
                <p class="text-sm"></p>
              </div>
              <hr class="vertical dark">
            </div>
            <div class="col-md-4 position-relative">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary"><span id="state2" countTo="{{ num_newspapers }}">0</span>+</h1>
                <h5 class="mt-3">Newspaper</h5>
                <p class="text-sm"></p>
              </div>
              <hr class="vertical dark">
            </div>
            <div class="col-md-4">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary" id="state3" countTo="{{ num_redactors }}">0</h1>
                <h5 class="mt-3">Redactors</h5>
                <p class="text-sm"></p>
              </div>
            </div>
            <div>

            </div>

          </div>

        </div>

      </div>

    </div>

  </section>


  <script src="{% static 'js/core/popper.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/core/bootstrap.min.js' %}" type="text/javascript"></script>
  <script src="?v=1.0.9" type="text/javascript"></script>

{% endblock content %}



{% block javascripts %}

  <script type="text/javascript">

      if (document.getElementById('state1')) {
          const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
          if (!countUp.error) {
              countUp.start();
          } else {
              console.error(countUp.error);
          }
      }
      if (document.getElementById('state2')) {
          const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
          if (!countUp1.error) {
              countUp1.start();
          } else {
              console.error(countUp1.error);
          }
      }
      if (document.getElementById('state3')) {
          const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
          if (!countUp2.error) {
              countUp2.start();
          } else {
              console.error(countUp2.error);
          }
          ;
      }
  </script>

{% endblock javascripts %}


templates/newspaper/newspaper_confirm_delete.html
{% extends 'layouts/base_sections.html' %}
{% load static %}

{% block title %} Soft UI Design System by Havrylyshyn Ivan {% endblock title %}
{% block body %} class="sign-in-illustration" {% endblock body %}

{% block header %}
  {% include 'includes/navigation.html' %}
{% endblock header %}

{% block content %}
  <header class="footer py-5">
    <div class="container ml-4">
      <div class="row">
        <div class="col-lg-8 mb-4 mx-auto text-center">
          <img class="max-width-500 w-100 position-relative z-index-2"
               src="{% static 'img/illustrations/chat.png' %}">
          <h1>Delete Newspaper</h1>
          <p>Are you sure you want delete the {{ object.title }}</p>
          <p><i>Newspaper will be also deleted!</i></p>
          <form action="" method="post">
            {% csrf_token %}
            <input type="submit" value="Yes, delete" class="btn btn-danger"/>
            <a href="{% url 'newspaper:newspapers-list' %}" class="btn btn-secondary">Cancel</a>
          </form>
        </div>
      </div>
    </div>
  </header>

  <script src="{% static 'js/core/popper.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/core/bootstrap.min.js' %}" type="text/javascript"></script>
  <script src="?v=1.0.9" type="text/javascript"></script>
{% endblock %}

{% block footer %}
  {% include 'includes/footer_fullscreen.html' %}
{% endblock footer %}

{% block javascripts %}
{% endblock javascripts %}

templates/newspaper/newspaper_detail.html
{% extends 'layouts/base_sections.html' %}
{% load static %}
{% load crispy_forms_filters %}
{% block title %} Soft UI Design System by Havrylyshyn Ivan {% endblock title %}

{% block body %} class="index-page bg-gray-200" {% endblock body %}

{% block header %}
  {% include 'includes/navigation.html' %}
{% endblock header %}

{% block content %}
  <header class="header-2">
    <div class="page-header min-vh-75 relative"
         style="background-image: url('{% static 'img/curved-images/curved17.jpg' %}')">
      <div class="container">
        <div class="row">
          <div class="page-header min-vh-75 relative">
            <div class="container mt-4" style="width: 75%; margin: 0 auto;">
              <table class="table text-white">
                <tr>

                  <h1 class="text-white">{{ object.title }}<a class="btn-secondary page-link" style="float: right"
                                                 href="{% url 'newspaper:newspaper-update' pk=object.id %}"> Edit</a>
                  </h1>
                </tr>
                <tr>
                  <p class="text-white"><strong>publishers</strong> {{ object.display_authors }}</p>
                </tr>
                <tr><p class="text-white"><strong>published_date</strong> {{ object.published_date }}</p>
                </tr>
                <tr>
                  <div class="ml-3">
                    <h3 class="text-white">Texts:</h3>
                    {% if object.context %}
                      <p class="text-white">{{ object.context }}</p>
                    {% else %}
                      <p class="text-white">No write text for news</p>
                    {% endif %}
                  </div>
                </tr>
                </tr>
              </table>





            </div>
          </div>
        </div>
      </div>

      <div class="position-absolute w-100 z-index-1 bottom-0">
        <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
             viewBox="0 24 150 40" preserveAspectRatio="none" shape-rendering="auto">
          <defs>
            <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z"/>
          </defs>
          <g class="moving-waves">
            <use xlink:href="#gentle-wave" x="48" y="-1" fill="rgba(255,255,255,0.40"/>
            <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.35)"/>
            <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.25)"/>
            <use xlink:href="#gentle-wave" x="48" y="8" fill="rgba(255,255,255,0.20)"/>
            <use xlink:href="#gentle-wave" x="48" y="13" fill="rgba(255,255,255,0.15)"/>
            <use xlink:href="#gentle-wave" x="48" y="16" fill="rgba(255,255,255,0.95"/>
          </g>
        </svg>
      </div>

    </div>

  </header>


  <script src="{% static 'js/core/popper.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/core/bootstrap.min.js' %}" type="text/javascript"></script>
  <script src="?v=1.0.9" type="text/javascript"></script>

{% endblock %}
{% block footer %}

  {% include 'includes/footer_fullscreen.html' %}

{% endblock footer %}

{% block javascripts %}

{% endblock javascripts %}

templates/newspaper/newspaper_list.html
{% extends 'layouts/base_sections.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} Material Kit 2 by Havrylyshyn Ivan {% endblock title %}

{% block body %} class="index-page bg-gray-200" {% endblock body %}

{% block content %}

  <header class="header-2">
    <div class="page-header min-vh-25 relative"
         style="background-image: url('{% static 'img/curved-images/curved17.jpg' %}')">

      <div class="position-absolute w-100 z-index-1 bottom-0">

        <div class="container mt-4" style="width: 50%; margin: 0 auto;">
          <div class="d-flex justify-content-between align-items-center">
            <h1><a class="btn btn-primary" style="float: right" href="{% url 'newspaper:newspaper-create' %}">+</a></h1>
            <form action="" method="get" class="form-inline d-flex">
              {{ search_form|crispy }}


              <input type="submit" value="🔎" class="btn btn-secondary">
            </form>
          </div>
        </div>
      </div>
    </div>
  </header>

  {% if newspaper_list %}
    <div class="page-header min-vh-50 relative"
         style="background-image: url('{% static 'img/curved-images/curved17.jpg' %}')">
      <div class="container">
        <div class="row">
          <div class="page-header min-vh-75 relative height-200">
            <div class="container mt-4" style="width: 100%; margin: 0 auto;">
              <div class="col-lg-9 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
                <table class="table">
                  <tr>
                    <th class="text-black-50">Topic</th>
                    <th>Title</th>
                    <th>Write by</th>
                    <th>Publish date</th>
                    <th>Update</th>
                    <th>Delete</th>
                  </tr>
                  {% for news in newspaper_list %}
                    <tr>
                      <td><a href="{{ news.get_absolute_url }}"/> {{ news.topic }}</td>
                      <td><a href="{{ news.get_absolute_url }}"/>{{ news.title }}</td>
                      <td><a href="{{ news.get_absolute_url }}"/>{{ news.display_authors }}</td>
                      <td>{{ news.published_date }}</td>
                      <td><a href="{% url 'newspaper:newspaper-update' pk=news.id %}">Update</a></td>
                      <td><a href="{% url 'newspaper:newspaper-delete' pk=news.id %}">Delete</a></td>
                    </tr>

                  {% endfor %}
                </table>

                {% else %}

                <p> There are no news</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  {% endif %}







  <script src="{% static 'js/core/popper.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/core/bootstrap.min.js' %}" type="text/javascript"></script>
  <script src="?v=1.0.9" type="text/javascript"></script>
{% endblock %}


templates/newspaper/redactors_list.html
{% extends 'layouts/base_sections.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} Material Kit 2 by Havrylyshyn Ivan {% endblock title %}

{% block body %} class="index-page bg-gray-200" {% endblock body %}

{% block content %}

  <header class="header-2">
    <div class="page-header min-vh-25 relative"
         style="background-image: url('{% static 'img/curved-images/curved15.jpg' %}')">

      <div class="position-absolute w-100 z-index-1 bottom-0">

        <div class="container mt-4" style="width: 50%; margin: 0 auto;">
          <div class="d-flex justify-content-between align-items-center">
            <h1><a class="btn btn-primary" style="float: right " href="{% url 'newspaper:redactor-create' %}">+</a></h1>
            <form action="" method="get" class="form-inline d-flex">
              {{ search_form |crispy }}
              <input type="submit" value="🔎" class="btn btn-secondary">
            </form>
          </div>
        </div>
      </div>
    </div>
  </header>

  {% if redactors_list %}
    <div class="page-header min-vh-20 relative"
         style="background-image: url('{% static 'img/curved-images/curved15.jpg' %}')">
      <div class="container">
        <div class="row">
          <div class="page-header min-vh-75 relative height-200">
            <div class="container mt-4" style="width: 100%; margin: 0 auto;">
              <div class="col-lg-9 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
                <table class="table">
                  <tr>
                    <th>Username</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Experience</th>
                    <th>Delete</th>

                  </tr>
                  {% for redactor in redactors_list %}
                    <tr>

                      <td><a href="{{ redactor.get_absolute_url }}"/>{{ redactor.username }}{% if user == redactor %}
                        (Me){% endif %}</td>
                      <td><a href="{{ redactor.get_absolute_url }}"/>{{ redactor.first_name }}</td>
                      <td><a href="{{ redactor.get_absolute_url }}"/>{{ redactor.last_name }}</td>
                      <td><a href="{{ redactor.get_absolute_url }}"/>{{ redactor.years_of_experience }}</td>
                      <td><a href="{% url 'newspaper:redactors-delete' pk=redactor.id %}">Delete</a></td>

                    </tr>

                  {% endfor %}
                </table>
                {% else %}
                <p>The are no redactors</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  {% endif %}


  <script src="{% static 'js/core/popper.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/core/bootstrap.min.js' %}" type="text/javascript"></script>
  <script src="?v=1.0.9" type="text/javascript"></script>
{% endblock %}


templates/newspaper/topic_form2.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <h1>{{ object|yesno:"Update, Create" }} Topic</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/newspaper/topics_list.html
{% extends 'layouts/base_sections.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} Material Kit 2 by Havrylyshyn Ivan {% endblock title %}

{% block body %} class="index-page bg-gray-200" {% endblock body %}

{% block content %}
  <header class="header-2">
    <div class="page-header min-vh-25 relative"
         style="background-image: url('{% static 'img/curved-images/curved15.jpg' %}')">

      <div class="position-absolute w-100 z-index-1 bottom-0">

        <div class="container mt-4" style="width: 50%; margin: 0 auto;">
          <div class="d-flex justify-content-between align-items-center">
            <h1><a class="btn btn-primary" style="float: right" href="{% url 'newspaper:topics-create' %}">+</a></h1>
            <form action="" method="get" class="form-inline d-flex">
              {{ search_form|crispy }}
              <input type="submit" value="🔎" class="btn btn-secondary">
            </form>
          </div>
        </div>
      </div>
    </div>
  </header>


  {% if topics_list %}
    <div class="page-header min-vh-20 relative"
         style="background-image: url('{% static 'img/curved-images/curved15.jpg' %}')">
      <div class="container">
        <div class="row">
          <div class="page-header min-vh-75 relative height-200">
            <div class="container mt-4" style="width: 100%; margin: 0 auto;">
              <div class="col-lg-9 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
                <table class="table">
                  <tr>
                    <th>Topic Name</th>
                    <th>Update</th>
                    <th>Delete</th>
                  </tr>
                  {% for topic in topics_list %}
                    <tr>
                      <td>{{ topic.name }}</td>
                      <td><a href="{% url 'newspaper:topic-update' pk=topic.id %}">Update</a></td>
                      <td><a href="{% url 'newspaper:topic-delete' pk=topic.id %}">Delete</a></td>
                    </tr>
                  {% endfor %}
                </table>
                {% else %}
                <p> The are no topics</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  {% endif %}

<script src="{% static 'js/core/popper.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/core/bootstrap.min.js' %}" type="text/javascript"></script>
  <script src="?v=1.0.9" type="text/javascript"></script>
{% endblock %}